"use strict";
let movieName = "Hulk";
let myname = "Sulyman";
let myage = 41;
let intro = `my name is ${myname} and my age is ${myage}`;
const myMood = true;
let fName = "Salman";
let lName = "Ali";
let fullName = `${fName} ${lName}`;
console.log(fullName);
let userAge = 52;
let productName = "Table";
let productPrice = 5200;
let productDetail = `Product Name is ${productName} and price is Rs.${productPrice}.`;
console.log(productDetail);
let numberofPet = 21;
let todayisbirthday = true;
let firstName = "John";
let lastName = "Doe";
let age = 30;
let userInfo = `User Information: First Name: ${firstName} Last Name: ${lastName} Age: ${age}`;
// let userinfo2: string = `user information: FirstName ${firstName}`;
console.log(userInfo);
